<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Jellyfin.Plugin.LanguageFailover</RootNamespace>
    <AssemblyName>Jellyfin.Plugin.LanguageFailover</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Jellyfin.Model">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Pages\configPage.html" />
    <EmbeddedResource Include="Pages\configPage.js" />
  </ItemGroup>

</Project>
